source 'https://rubygems.org'

ruby '>= 2.7.0'

# Web Framework
gem 'sinatra', '~> 3.0'
gem 'sinatra-contrib', '~> 3.0'
gem 'puma', '~> 6.0'

# Database
gem 'activerecord', '~> 7.0'
gem 'sqlite3', '~> 1.6' # Using SQLite as Oracle replacement for development
gem 'standalone_migrations', '~> 7.1'

# HTTP Client for service communication
gem 'httparty', '~> 0.21'

# JSON
gem 'json', '~> 2.6'

# Environment variables
gem 'dotenv', '~> 2.8'

# Validation
gem 'dry-validation', '~> 1.10'

group :development, :test do
  gem 'rspec', '~> 3.12'
  gem 'rack-test', '~> 2.1'
  gem 'database_cleaner-active_record', '~> 2.1'
  gem 'factory_bot', '~> 6.2'
  gem 'faker', '~> 3.2'
  gem 'webmock', '~> 3.19'
end
