require 'standalone_migrations'
StandaloneMigrations::Tasks.load_tasks

task :environment do
  require_relative 'config/environment'
end

namespace :db do
  desc 'Run database migrations'
  task :migrate => :environment do
    ActiveRecord::Base.logger = Logger.new(STDOUT)
    ActiveRecord::Migration.verbose = true
    ActiveRecord::Migrator.migrate('db/migrate')
  end

  desc 'Rollback database migration'
  task :rollback => :environment do
    ActiveRecord::Base.logger = Logger.new(STDOUT)
    ActiveRecord::Migration.verbose = true
    ActiveRecord::Migrator.rollback('db/migrate', 1)
  end
end
