source 'https://rubygems.org'

ruby '>= 2.7.0'

# Web Framework
gem 'sinatra', '~> 3.0'
gem 'sinatra-contrib', '~> 3.0'
gem 'puma', '~> 6.0'

# NoSQL Database
gem 'mongo', '~> 2.19'

# JWT for service-to-service authentication
gem 'jwt', '~> 2.7'

# RabbitMQ for async messaging
gem 'bunny', '~> 2.22'

# JSON
gem 'json', '~> 2.6'

# CORS support for Swagger UI
gem 'rack-cors', '~> 2.0'

# Environment variables
gem 'dotenv', '~> 2.8'

# Validation
gem 'dry-validation', '~> 1.10'

group :development, :test do
  gem 'rspec', '~> 3.12'
  gem 'rack-test', '~> 2.1'
  gem 'faker', '~> 3.2'
  gem 'webmock', '~> 3.18'
  gem 'simplecov', '~> 0.22', require: false
end
